name: vt-franka-controller
channels:
  - pytorch
  - fair-robotics
  - aihabitat
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - fastapi
  - uvicorn
  - pydantic>=2.6
  - pyyaml
  - requests
  - pip:
      - -e ../shared
      - -e .
