server:
  host: 0.0.0.0
  port: 8092

backend:
  kind: polymetis
  robot_ip: 127.0.0.1
  robot_port: 50051
  gripper_ip: 127.0.0.1
  gripper_port: 50052

control:
  control_frequency_hz: 300.0
  teleop_command_hz: 60.0
  state_cache_hz: 60.0
  cartesian_stiffness: [750.0, 750.0, 750.0, 15.0, 15.0, 15.0]
  cartesian_damping: [37.0, 37.0, 37.0, 2.0, 2.0, 2.0]
  home_ee_pose: [0.1, 0.4, 0.4, 180, 0, 45] # position in meters and orientation in degrees (roll, pitch, yaw)
  home_duration_sec: 8.0
  ready_ee_pose: [0.1, 0.4, 0.4, 180, 0, 45] # position in meters and orientation in degrees (roll, pitch, yaw)
  ready_duration_sec: 5.0
  max_queue_size: 256
