name: vt-franka-workspace
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - fastapi
  - uvicorn
  - requests
  - pyyaml
  - pip:
      - -e ../shared
      - -e .
